version: '3.8'

services:
  app:
    build:
      context: .         # 프로젝트 루트 디렉토리를 빌드 컨텍스트로 설정
      dockerfile: app/Dockerfile  # Dockerfile은 여전히 app 폴더에 위치
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      # 직접 변수값을 사용해도 되지만, 치환 방식을 사용하면 .env에 정의된 값이 자동 적용됨
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
