version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"  # 윈도우에서 FastAPI 접속 가능
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: db  # MySQL은 내부 네트워크에서만 연결
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db
    networks:
      - shared_network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shared_network
    # MySQL 포트 개방하지 않음 (WSL 내부에서만 접근 가능)

volumes:
  db_data:

networks:
  shared_network:
    driver: bridge  # FastAPI와 MySQL이 같은 내부 네트워크에서 통신
