
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # 루트에 위치한 Dockerfile 사용
    container_name: fastapi_app
    ports:
      - "8000:8000"  # 외부 포트:컨테이너 포트
    environment:
      # AWS RDS MySQL 연결
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: ${MYSQL_HOST}  # AWS RDS 엔드포인트 사용
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      # MongoDB 연결 및 CSV 업로드 관련 환경변수들
      MONGO_URL: ${MONGO_URL}
      COLLECTION_1: ${COLLECTION_1}
      COLLECTION_2: ${COLLECTION_2}
      COLLECTION_3: ${COLLECTION_3}
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge
